### ISSUE TITLE
Where is the semantic.csv file?

### ISSUE THREAD

**Issue by zhanwuzhazha** [Aryan-2003/Book-Recommendation-System#1]
Hi there,

I'm trying to run the code from your repository, but I'm having trouble finding the semantic.csv file. Could you please let me know where I can find this file or how I can generate it?

Thank you in advance for your help!

**Comment by Aryan-2003** [comment]
Hi @zhanwuzhazha ,
Sorry for the late reply. 
https://www.kaggle.com/datasets/aryan2003/ratings
Here you will find the file....
